import { Product } from "./types";

// Catalogue statique pour le Lot 1. Sera remplacé par une source
// backend (base de données) au Lot 2.
export const products: Product[] = [
  {
    id: "chicha-solo",
    name: "Chicha Solo",
    description: "Narguilé, charbon naturel et saveur au choix. Pour 1 à 2 personnes.",
    price: 19.9,
    emoji: "💨",
    category: "Chichas",
  },
  {
    id: "chicha-duo",
    name: "Chicha Duo",
    description: "Format généreux, deux saveurs au choix. Pour 2 à 3 personnes.",
    price: 24.9,
    emoji: "💨",
    category: "Chichas",
  },
  {
    id: "chicha-party",
    name: "Chicha Party",
    description: "Le grand format pour vos soirées. Pour 4 à 6 personnes.",
    price: 34.9,
    emoji: "🎉",
    category: "Chichas",
  },
  {
    id: "recharge-double-pomme",
    name: "Recharge Double Pomme",
    description: "Pot de 50g, la saveur classique et intemporelle.",
    price: 6.5,
    emoji: "🍏",
    category: "Saveurs & Recharges",
  },
  {
    id: "recharge-menthe-glaciale",
    name: "Recharge Menthe Glaciale",
    description: "Pot de 50g, fraîcheur intense.",
    price: 6.5,
    emoji: "🌿",
    category: "Saveurs & Recharges",
  },
  {
    id: "recharge-raisin-menthe",
    name: "Recharge Raisin Menthe",
    description: "Pot de 50g, douceur fruitée et mentholée.",
    price: 6.5,
    emoji: "🍇",
    category: "Saveurs & Recharges",
  },
  {
    id: "charbon-coco",
    name: "Charbon naturel noix de coco",
    description: "Plateau de charbons naturels, combustion longue et propre.",
    price: 4.9,
    emoji: "🔥",
    category: "Saveurs & Recharges",
  },
  {
    id: "embouts-jetables",
    name: "Embouts jetables",
    description: "Lot de 10, pour une utilisation individuelle et hygiénique.",
    price: 2.9,
    emoji: "🔘",
    category: "Saveurs & Recharges",
  },
  {
    id: "the-menthe",
    name: "Thé à la menthe maison",
    description: "Infusé et servi frais.",
    price: 3.5,
    emoji: "🍵",
    category: "Boissons",
  },
  {
    id: "soda-artisanal",
    name: "Soda artisanal",
    description: "Sélection de sodas artisanaux.",
    price: 3.9,
    emoji: "🥤",
    category: "Boissons",
  },
];
