import { Product } from "./types";

// Catalogue Smoak Paris — boissons fraîches / épicerie sucrée. La chicha
// (Quasar / Khaloud, goûts, recharge, suppléments) est composée à part via
// le composeur, voir src/lib/chicha.ts.
//
// ⚠️ Prix provisoires — à valider avant mise en vente. Restent aussi à
// définir : les formats/fournisseurs précis (canettes, jus, bonbons,
// chocolat Dubaï), les stocks de départ et les quantités maximum par
// commande.
export const products: Product[] = [
  // Boissons — canettes, énergisantes, 1,5 L et jus.
  {
    id: "canette-coca-cola",
    name: "Coca-Cola",
    description: "Canette.",
    price: 2,
    emoji: "🥤",
    category: "Boissons",
    image: "/produits/Coca_Boisson.png",
  },
  {
    id: "canette-coca-cherry",
    name: "Coca-Cola Cherry",
    description: "Canette.",
    price: 2,
    emoji: "🥤",
    category: "Boissons",
    image: "/produits/Coca_Cherry_Boisson.png",
  },
  {
    id: "canette-coca-zero",
    name: "Coca-Cola Zero",
    description: "Canette.",
    price: 2,
    emoji: "🥤",
    category: "Boissons",
    image: "/produits/Coca_Zero.png",
  },
  {
    id: "canette-fanta",
    name: "Fanta",
    description: "Canette.",
    price: 2,
    emoji: "🥤",
    category: "Boissons",
    image: "/produits/Fanta.png",
  },
  {
    id: "canette-hawaii",
    name: "Hawaii",
    description: "Canette.",
    price: 2,
    emoji: "🥤",
    category: "Boissons",
    image: "/produits/Hawai_Boisson.png",
  },
  {
    id: "canette-oasis-cassis",
    name: "Oasis Cassis",
    description: "Canette.",
    price: 2,
    emoji: "🥤",
    category: "Boissons",
    image: "/produits/Oasis_Cassis_.png",
  },
  {
    id: "canette-oasis-fraise",
    name: "Oasis Fraise",
    description: "Canette.",
    price: 2,
    emoji: "🥤",
    category: "Boissons",
    image: "/produits/Oasis_Fraise.png",
  },
  {
    id: "canette-oasis-pomme-poire",
    name: "Oasis Pomme Poire",
    description: "Canette.",
    price: 2,
    emoji: "🥤",
    category: "Boissons",
    image: "/produits/Oasis_Pomme_Poire.png",
  },
  {
    id: "canette-oasis-tropical",
    name: "Oasis Tropical",
    description: "Canette.",
    price: 2,
    emoji: "🥤",
    category: "Boissons",
    image: "/produits/Oasis_Tropical.png",
  },
  {
    id: "canette-orangina",
    name: "Orangina",
    description: "Canette.",
    price: 2,
    emoji: "🥤",
    category: "Boissons",
    image: "/produits/Orangina.png",
  },
  {
    id: "canette-schweppes-agrumes",
    name: "Schweppes Agrumes",
    description: "Canette.",
    price: 2,
    emoji: "🥤",
    category: "Boissons",
    image: "/produits/Schwepps_Agrume.png",
  },
  {
    id: "canette-dada-litchi",
    name: "Dada Litchi",
    description: "Canette.",
    price: 2,
    emoji: "🥤",
    category: "Boissons",
    image: "/produits/Dada_Litchi.png",
  },
  {
    id: "canette-dada-mangue",
    name: "Dada Mangue",
    description: "Canette.",
    price: 2,
    emoji: "🥤",
    category: "Boissons",
    image: "/produits/Dada_Mangue.png",
  },
  {
    id: "canette-dada-melon",
    name: "Dada Melon",
    description: "Canette.",
    price: 2,
    emoji: "🥤",
    category: "Boissons",
    image: "/produits/Dada_Melon.png",
  },
  {
    id: "canette-ice-tea-peche",
    name: "Ice Tea Pêche",
    description: "Canette.",
    price: 2,
    emoji: "🥤",
    category: "Boissons",
    image: "/produits/ice_tea_peche.png",
  },
  {
    id: "red-bull",
    name: "Red Bull",
    description: "Boisson énergisante.",
    price: 3,
    emoji: "⚡",
    category: "Boissons",
    image: "/produits/RedBull_classique.png",
  },
  {
    id: "red-bull-zero",
    name: "Red Bull Zero",
    description: "Boisson énergisante.",
    price: 3,
    emoji: "⚡",
    category: "Boissons",
    image: "/produits/RedBull_Zero.png",
  },
  {
    id: "crazy-tiger",
    name: "Crazy Tiger",
    description: "Bouteille 1 L.",
    price: 5.9,
    emoji: "⚡",
    category: "Boissons",
    image: "/produits/crazy_tiger_1L.png",
  },
  {
    id: "eau-cristalline-50cl",
    name: "Cristalline 50 cl",
    description: "Bouteille d'eau 50 cl.",
    price: 1.5,
    emoji: "💧",
    category: "Boissons",
    image: "/produits/cristalline_50cl.png",
  },
  {
    id: "coca-cola-1-5l",
    name: "Coca-Cola 1,5 L",
    description: "Bouteille 1,5 L.",
    price: 4.5,
    emoji: "🧴",
    category: "Boissons",
    image: "/produits/coca_1L5.png",
  },
  {
    id: "oasis-1-5l",
    name: "Oasis 1,5 L",
    description: "Bouteille 1,5 L.",
    price: 4.5,
    emoji: "🧴",
    category: "Boissons",
    image: "/produits/Oasis_1L5.png",
  },
  {
    id: "jus-pomme-1l",
    name: "Jus de pomme 1 L",
    description: "Bouteille 1 L.",
    price: 3.9,
    emoji: "🧃",
    category: "Boissons",
    image: "/produits/Jus_de_pomme_1L.png",
  },

  // Épicerie sucrée
  {
    id: "bonbons-fini-arc-en-ciel",
    name: "Fini Arc-en-ciel",
    description: "Bonbons Fini goût arc-en-ciel.",
    price: 2.9,
    emoji: "🍬",
    category: "Épicerie sucrée",
    image: "/produits/Arc-en-ciel_fini.png",
  },
  {
    id: "bonbons-fini-pasteque",
    name: "Fini Pastèque",
    description: "Bonbons Fini goût pastèque.",
    price: 2.9,
    emoji: "🍬",
    category: "Épicerie sucrée",
    image: "/produits/Fini_Pasteque.png",
  },
  {
    id: "bonbons-fini-peches",
    name: "Fini Pêches",
    description: "Bonbons Fini goût pêches.",
    price: 2.9,
    emoji: "🍬",
    category: "Épicerie sucrée",
    image: "/produits/fini_peches.png",
  },
  {
    id: "bonbons-fini-fraise",
    name: "Fini Fraise",
    description: "Bonbons Fini goût fraise.",
    price: 2.9,
    emoji: "🍬",
    category: "Épicerie sucrée",
    image: "/produits/Fini_fraise.png",
  },
  {
    id: "popcorn-caramel",
    name: "Popcorn Caramel",
    description: "Popcorn au caramel.",
    price: 3.9,
    emoji: "🍿",
    category: "Épicerie sucrée",
    image: "/produits/Popcorn_caramel.png",
  },
];
